Fri, 25 Oct 2019 16:48:38 loganWatchTestCase.py[line:31] INFO 12345
Fri, 25 Oct 2019 16:48:38 loganWatchTestCase.py[line:32] DEBUG debug
Fri, 25 Oct 2019 16:48:38 loganWatchTestCase.py[line:33] ERROR error
Fri, 25 Oct 2019 16:48:38 connectionpool.py[line:206] DEBUG Starting new HTTP connection (1): 127.0.0.1:49391
Fri, 25 Oct 2019 16:48:58 connectionpool.py[line:396] DEBUG http://127.0.0.1:49391 "GET http://192.168.1.3:80/api2/bed/bind HTTP/1.1" 503 None
